---
name: Link Check Built Pages

on:
  schedule:
    - cron: 0 9 1 * *
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@1d0c1c7ee84f9247bcc05de363808eda0d1243ea # v0
        with:
          branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
